AllCops:
  TargetRubyVersion: 3.0

  NewCops: enable

  DisplayCopNames: true
  DisplayStyleGuide: false

  Exclude:
    - './_site/**/*'
    - vendor/**/*

require:
  - rubocop-performance
  - rubocop-rake

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 20

# It's actually quite cool to spell my own name correctly...
Style/AsciiComments:
  Enabled: false
