require:
  - rubocop-performance
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.0

  NewCops: enable

  DisplayCopNames: true
  DisplayStyleGuide: false

  Exclude:
    - './_site/**/*'

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 20

# This forces us to create a new object for no real reason.
Style/MultipleComparison:
  Enabled: false

# It's actually quite cool to spell my own name correctly...
Style/AsciiComments:
  Enabled: false
