---

title: Miquel Sabaté Solà
name: Miquel
author: Miquel Sabaté Solà
email: mikisabate@gmail.com
twitter_username: miquelssola
description: El meu espai personal en un oceà immens.

exclude: [LICENSE, README.org, yarn.lock, Gemfile, Gemfile.lock, config,
          node_modules, vendor, templates, yarn-error.log, package.json,
          javascripts/main.js]

timezone: "Europe/Berlin"
markdown: kramdown
highlighter: rouge
encoding: UTF-8

# No subpath required.
baseurl: ""

# The base hostname & protocol.
url: "http://jo.mssola.com"

sass:
  style: compressed
  sass_dir: ./stylesheets/partials

plugins:
  - jekyll-multiple-languages-plugin
  - jemoji

languages: ["ca", "en"]
exclude_from_localizations: ["javascript", "images", "stylesheets"]
