#!/usr/bin/env bash
# Copyright (C) 2018-2020 Miquel Sabaté Solà <mikisabate@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

#
# This script is based on the one from the documentation of Jekyll.
#

NAME=jo
GIT_REPO=$HOME/$NAME.git
TARGET_BRANCH=main

# Exported so it's picked by the `script/docker-build.sh` script.
export BUILD_SOURCE=$HOME/tmp/$NAME
export BUILD_DEST=/srv/$NAME/www

while read oldrev newrev refname
do
    branch=$(git rev-parse --symbolic --abbrev-ref $refname)
    if [ -n "$branch" ] && [ "$TARGET_BRANCH" == "$branch" ]; then
      set -x

      # Re-generate git repository in a temporary directory.
      rm -Rf $BUILD_SOURCE
      git clone --branch $TARGET_BRANCH $GIT_REPO $BUILD_SOURCE

      # Build site
      chmod +x $BUILD_SOURCE/script/docker-build.sh
      cd $BUILD_SOURCE
      POST_RECEIVE=true NUKE=true $BUILD_SOURCE/script/docker-build.sh
    fi
done
